function Generate-SecureString ($length = 64) {
    $bytes = New-Object Byte[] $length
    $rng = [System.Security.Cryptography.RNGCryptoServiceProvider]::Create()
    $rng.GetBytes($bytes)
    return [Convert]::ToBase64String($bytes).Replace('+', '-').Replace('/', '_').TrimEnd('=')
}

function Generate-AesKey {
    $bytes = New-Object Byte[] 32
    $rng = [System.Security.Cryptography.RNGCryptoServiceProvider]::Create()
    $rng.GetBytes($bytes)
    return [Convert]::ToBase64String($bytes)
}

$envPath = Join-Path $PSScriptRoot "..\.env"

$jwtSecret = (Generate-SecureString 64).Substring(0, 64)
$anonKey = Generate-SecureString 128
$serviceRoleKey = Generate-SecureString 128
$dbPassword = (Generate-SecureString 32).Substring(0, 32)
$devAesKey = Generate-AesKey

$envContent = @"
# ==========================================
# ANTIGRAVITY LOCAL DEVELOPMENT SECRETS
# ==========================================
# AUTO-GENERATED BY SYSTEM SCRIPT (PowerShell)
# Environment: local/development

# [SUPABASE CORE]
POSTGRES_PASSWORD=$dbPassword
JWT_SECRET=$jwtSecret
ANON_KEY=$anonKey
SERVICE_ROLE_KEY=$serviceRoleKey

# [NEXT.JS APPLICATION]
NEXT_PUBLIC_SUPABASE_URL=http://localhost:8000
NEXT_PUBLIC_SUPABASE_ANON_KEY=$anonKey
SUPABASE_SERVICE_ROLE_KEY=$serviceRoleKey

# [ALE ENCRYPTION - LOCAL DEV ONLY]
# In production, this must be replaced by AWS KMS ARNs
LOCAL_DEV_AES_GCM_KEY=$devAesKey
PHI_ENCRYPTION_KEY_ID=local_dev_only

# [TELEMETRY & APM]
SIGNOZ_OTLP_ENDPOINT=http://localhost:4317

# [WAL-G LOCAL STUB]
WALG_S3_PREFIX=s3://local-dev-bucket/antigravity-walg
"@

Set-Content -Path $envPath -Value $envContent -Encoding UTF8

Write-Host "✅ Successfully generated development .env file at $envPath" -ForegroundColor Green
Write-Host "⚠️  WARNING: These are LOCAL development keys only. Never use in production." -ForegroundColor Yellow
