import os
import secrets
import base64

def generate_secure_string(length=64):
    """Generates a cryptographically secure random string."""
    return secrets.token_urlsafe(length)

def generate_aes_key():
    """Generates a base64 encoded 256-bit AES key for local development."""
    key = secrets.token_bytes(32)
    return base64.b64encode(key).decode('utf-8')

def create_env_file():
    """Creates the necessary .env file with generated secrets for Supabase and Antigravity."""
    env_path = os.path.join(os.path.dirname(__file__), '..', '.env')
    
    # Generate Secrets
    jwt_secret = generate_secure_string(64)
    anon_key = generate_secure_string(128) # In a real Supabase setup, this requires signing with the JWT secret
    service_role_key = generate_secure_string(128) # Same here
    db_password = generate_secure_string(32)
    dev_aes_key = generate_aes_key()

    env_content = f"""# ==========================================
# ANTIGRAVITY LOCAL DEVELOPMENT SECRETS
# ==========================================
# AUTO-GENERATED BY SYSTEM SCRIPT
# Environment: local/development

# [SUPABASE CORE]
POSTGRES_PASSWORD={db_password}
JWT_SECRET={jwt_secret}
ANON_KEY={anon_key}
SERVICE_ROLE_KEY={service_role_key}

# [NEXT.JS APPLICATION]
NEXT_PUBLIC_SUPABASE_URL=http://localhost:8000
NEXT_PUBLIC_SUPABASE_ANON_KEY={anon_key}
SUPABASE_SERVICE_ROLE_KEY={service_role_key}

# [ALE ENCRYPTION - LOCAL DEV ONLY]
# In production, this must be replaced by AWS KMS ARNs
LOCAL_DEV_AES_GCM_KEY={dev_aes_key}
PHI_ENCRYPTION_KEY_ID=local_dev_only

# [TELEMETRY & APM]
SIGNOZ_OTLP_ENDPOINT=http://localhost:4317

# [WAL-G LOCAL STUB]
WALG_S3_PREFIX=s3://local-dev-bucket/antigravity-walg
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"✅ Successfully generated development .env file at {env_path}")
    print("⚠️  WARNING: These are LOCAL development keys only. Never use in production.")

if __name__ == "__main__":
    create_env_file()
